name: Build XMRig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - if: matrix.os == 'macos-latest'
        run: brew install cmake hwloc libuv openssl
      - if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          vcpkg install libuv:x64-windows hwloc:x64-windows openssl:x64-windows
          echo "CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
          
      - run: mkdir build && cd build
      - working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_HWLOC=ON -DWITH_TLS=ON -DWITH_OPENCL=OFF
      - working-directory: build
        run: cmake --build . --config Release --parallel $(nproc || sysctl -n hw.logicalcpu || echo 4)
      - uses: actions/upload-artifact@v4
        with:
          name: xmrig-${{ matrix.os }}
          path: build/xmrig*
