name: Build XMRig

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libhwloc-dev libuv1-dev
      - if: matrix.os == 'macos-latest'
        run: brew install hwloc libuv
      - if: matrix.os == 'windows-latest'
        name: Clone xmrig-deps
        run: git clone https://github.com/xmrig/xmrig-deps.git deps

      - run: mkdir build && cd build
      - if: matrix.os == 'windows-latest'
        working-directory: build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64 -DXMRIG_DEPS=c:\xmrig-deps\msvc2022\x64
      - if: matrix.os != 'windows-latest'
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
      - working-directory: build
        run: cmake --build . --config Release --parallel
        
      - uses: actions/upload-artifact@v4
        with:
          name: xmrig-${{ matrix.os }}
          path: build/xmrig*
